// Server component — SplitTextReveal is its own 'use client' island,
// so this file can stay on the server and import node-only fs.
import { existsSync } from 'fs';
import { join } from 'path';
import Image from 'next/image';
import Link from 'next/link';
import { SplitTextReveal } from '../_components/SplitTextReveal';

// Resolved at module load (server-side) — Next inlines this as a boolean
// at build time. If the user hasn't run `npm run gen:hero` yet, we show
// the placeholder; once /public/hero.png exists, the real photo renders.
const HERO_IMAGE_EXISTS = existsSync(join(process.cwd(), 'public', 'hero.png'));

/**
 * Section 1 — Hero.
 * Motion: splittext-reveal on the headline (fires on mount, not on scroll).
 * Imagery: placeholder slot. Replace with a real product photograph
 * generated via Nano Banana before launch.
 */
export function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div className="mx-auto max-w-6xl px-6 pt-20 pb-28 md:pt-32 md:pb-40">
        <p className="font-mono text-xs uppercase tracking-widest text-slate2 mb-8">
          For drivers · for fleets
        </p>

        <SplitTextReveal
          as="h1"
          onScroll={false}
          className="text-5xl md:text-7xl font-medium tracking-tight text-ink max-w-4xl leading-[1.05]"
        >
          A second opinion for your car.
        </SplitTextReveal>

        <p className="mt-8 text-lg md:text-xl text-slate2 max-w-prose leading-relaxed">
          CarFai watches your maintenance receipts, OBD2 codes, and
          ownership history, then tells you what they actually mean —
          using your data, not the internet's.
        </p>

        <div className="mt-10 flex flex-wrap items-center gap-4">
          <a
            href="#start"
            className="inline-flex items-center gap-2 px-5 py-3 rounded-full bg-accent text-white hover:bg-accentDeep transition-colors font-medium"
          >
            Start free
            <span aria-hidden>→</span>
          </a>
          <Link
            href="/pricing"
            className="inline-flex items-center gap-2 px-5 py-3 text-ink hover:text-accentDeep transition-colors font-medium"
          >
            See pricing
          </Link>
        </div>

        {/*
          Hero imagery. Generated by `npm run gen:hero` (Nano Banana /
          Gemini 2.5 Flash Image — see scripts/generate-hero.mjs).
          Placeholder shows until /public/hero.png exists.
        */}
        <div className="mt-20 relative aspect-[16/9] rounded-2xl border border-rule bg-paperDeep overflow-hidden">
          {HERO_IMAGE_EXISTS ? (
            <Image
              src="/hero.png"
              alt="Close-up of a car's instrument cluster at golden hour."
              fill
              priority
              sizes="(min-width: 1280px) 1100px, 95vw"
              className="object-cover"
            />
          ) : (
            <div className="absolute inset-0 flex items-center justify-center">
              <p className="font-mono text-xs uppercase tracking-widest text-slate2">
                hero image slot — run `npm run gen:hero`
              </p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
